### ISSUE TITLE
More notification

### ISSUE THREAD

**Issue by Fastbyte01** [ghinda/nudgeti#2]
Hi, it's possible to to make sure that the notification appear more time.

For example I used the standard settings of 2 minutes.

The notification appear after 2 minutes, 4 minutes and after that stopped appearing. I have tested on facebook and youtube for 30 minutes.

**Comment by ghinda** [comment]
It's not possible right now, but if more people ask for it I will implement a configuration option.

**Comment by cakeslice** [comment]
Yeah this would be great, it's easy to ignore the notifications and then you never stop procrastinating :D

Great work btw! ⭐️ ⭐️ ⭐️ ⭐️ ⭐️

**Comment by ghinda** [comment]
Released `0.3.0` with a setting for the number of repetitions:
![screenshot_20180703_121444](https://user-images.githubusercontent.com/325171/42211106-6648da84-7ebb-11e8-93f6-f83d9d1acb30.png)

You can also set it to "indefinetely". 

Thanks for the feedback!
